# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{beanstalkapp}
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Sabanin"]
  s.date = %q{2010-01-20}
  s.email = %q{ilya.sabanin@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "beanstalkapp.gemspec",
     "lib/beanstalkapp.rb",
     "lib/beanstalkapp/account.rb",
     "lib/beanstalkapp/base.rb",
     "lib/beanstalkapp/changeset.rb",
     "lib/beanstalkapp/comment.rb",
     "lib/beanstalkapp/release.rb",
     "lib/beanstalkapp/release_server.rb",
     "lib/beanstalkapp/repository.rb",
     "lib/beanstalkapp/user.rb"
  ]
  s.homepage = %q{http://api.beanstalkapp.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Official wrapper for Beanstalk API.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activeresource>, ["= 2.3.5"])
    else
      s.add_dependency(%q<activeresource>, ["= 2.3.5"])
    end
  else
    s.add_dependency(%q<activeresource>, ["= 2.3.5"])
  end
end

